# Generated by Django 3.1.7 on 2021-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('search_head', models.CharField(max_length=100)),
                ('string', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=100)),
                ('data', models.TextField()),
            ],
        ),
    ]
