# Generated by Django 3.1.7 on 2021-05-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
