# Generated by Django 3.1.7 on 2021-04-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
