# Generated by Django 3.1.7 on 2021-04-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20210429_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
