# Generated by Django 3.1.7 on 2021-05-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
