# Generated by Django 3.1.7 on 2021-04-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
