# Generated by Django 3.1.7 on 2021-04-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_post',
        ),
        migrations.AddField(
            model_name='profile',
            name='post_data',
            field=models.ManyToManyField(to='blogapp.Post'),
        ),
    ]
