# Generated by Django 3.1.7 on 2021-05-04 03:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
