# Generated by Django 3.1.7 on 2021-05-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_auto_20210503_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
