# Generated by Django 3.1.7 on 2021-04-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20210410_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
