# Generated by Django 3.1.7 on 2021-05-04 03:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=tinymce.models.HTMLField(),
        ),
    ]
