# Generated by Django 3.1.7 on 2021-04-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
