# Generated by Django 3.1.7 on 2021-04-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(to='blogapp.Post'),
        ),
    ]
