# Generated by Django 3.1.7 on 2021-05-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_auto_20210505_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
