# Generated by Django 3.1.7 on 2021-05-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_post_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
    ]
