# Generated by Django 3.1.7 on 2021-04-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_auto_20210410_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
