# Generated by Django 3.1.7 on 2021-04-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_auto_20210410_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(blank=True, to='blogapp.Post'),
        ),
    ]
