# Generated by Django 3.1.7 on 2021-04-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_auto_20210410_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.SlugField(blank=True, verbose_name='username'),
        ),
    ]
