# Generated by Django 3.1.7 on 2021-05-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_auto_20210508_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
