# Generated by Django 3.1.7 on 2021-04-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_auto_20210411_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_img',
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.SlugField(),
        ),
    ]
