# Generated by Django 3.1.7 on 2021-05-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0024_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
