# Generated by Django 3.1.7 on 2021-05-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0027_auto_20210508_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
