# Generated by Django 3.1.7 on 2021-05-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0028_remove_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
    ]
