# Generated by Django 3.1.7 on 2021-05-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0029_remove_post_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
